name: container-build&push
description: its for docker build and push
inputs:
      app-name:
        type: string
        required: true
      registry:
        type: string
        required: true
      registry-name:
        type: string
        required: true
      username:
        type: string
        required: true
      password:
        type: string
        required: true
      docker-file-path:
        type: string
        required: true
      port:
        type: number
        required: false

runs:
  using: composite
  steps:
      - name: docker-login
        uses: docker/login-action@v4
        with:
          username: ${{inputs.username}}
          password: ${{inputs.password}}
          registry: ${{inputs.registry}}
      - name: container build
        working-directory: ${{github.workspace}}/dockerFiles
        shell: bash
        id: buildID
        run: |
          port=${{inputs.port}}
          pwd
          ls
          "if [ -n $port]; then
          docker build ${{inputs.app-name}} -p $port:$port -t ${{inputs.registry-name}}/${{inputs.app-name}}:latest
          else
            docker build ${{inputs.app-name}} -t ${{inputs.registry-name}} 
          fi"
      - name: set output
        if: success()
        run: |
            echo "res=success" >> "$GITHUB_OUTPUT"
        shell: bash
