name: Container test
on:
  workflow_dispatch:
    inputs:
      username:
        type: string
        required: true
      registry:
        type: string
        required: true
      registry_address:
        required: true
        type: string
  workflow_call:
    inputs:
      username:
        type: string
        required: true
      password:
        type: string
        required: true
      registry:
        type: string
        required: true
      registry_address:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        uses: docker/login-action@v4
        with:
          username: ${{inputs.username}}
          password: ${{secrets.GITHUB_TOKEN}}
          registry: ${{inputs.registry}}
      - name: pull the image
        id: container-run
        run: |
          docker pull ${{inputs.registry_address}}
          docker run -d --name myapp -p 3000:3000 ${{inputs.registry_address}}
          echo "res=success" >> "$GITHUB_OUTPUTS"
    outputs:
      result: ${{steps.container-run.outputs.res}}
          
    
