name: Container test
on:
  workflow_dispatch:
    inputs:
      username:
        type: string
        required: true
      registry:
        type: string
        required: true
      registry_address:
        required: true
        type: string
  workflow_call:
    inputs:
      username:
        type: string
        required: true
      registry:
        type: string
        required: true
      registry_address:
        required: true
        type: string
    secrets:
      password:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        uses: docker/login-action@v4
        with:
          username: ${{inputs.username}}
          password: ${{secrets.password}}
          registry: ${{inputs.registry}}
      - name: pull the image
        id: container-run
        run: |
          docker pull ${{inputs.registry_address}}
          docker run --name myapp -p 3000:3000 ${{inputs.registry_address}}
          echo "res=success" >> "$GITHUB_OUTPUT"
    outputs:
      result: ${{steps.container-run.outputs.res}}
          
    
