name: production deployment
description: deploy the dev app to the production
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  packages: write
  contents: write
  id-token: write

jobs:
  tag-prod-container:
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        uses: docker/login-action@v4
        with:
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          registry: ghcr.io
      - name: pull and tag the image
        run: |
          docker pull ghcr.io/foundone1/dev/sampleimage:v2
          docker tag ghcr.io/foundone1/dev/sampleimage:v2 ghcr.io/foundone1/prod/prodimage:v2
      - name: push the prod image
        run: |
          docker push ghcr.io/foundone1/prod/prodimage:v2
      - name: login to azure
        uses: azure/login@v2
        with:
          client-id: ${{secrets.CLIENT_ID}}
          tenant-id: ${{secrets.TENANT_ID}}
          subscription-id: ${{secrets.SUBSCRIPTION_ID}}
      - name: azure container apps deployment
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: app2-prod
          appSourcePath: ${{github.workspace}}
          registry: ghcr.io
          images: ghcr.io/foundone1/prod/prodimage:v2
          resoureGroup: grp2-prod
        
      
