name: deploy the app
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_run:
    types: completed
    workflows: [Docker App]

permissions:
  id-token: write
  contents: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: check the values
        run: |
          echo ${{secrets.CLIENT_ID}}
          echo ${{secrets.TENANT_ID}}
      - name: connect azure
        uses: azure/login@v2
        with:
          client-id: ${{secrets.CLIENT_ID}}
          tenant-id: ${{secrets.TENANT_ID}}
          subscription-id: ${{secrets.SUBSCRIPTION_ID}}
      - name: deploy the app
        uses: azure/container-apps-deoploy-action@v1
        with:
          containerAppName: app1
          registryServer: ghcr.io
          registryUsername: VickyR16
          registryPassword: ${{secrets.GITHUB_TOKEN}}
          imageToDeploy: ghcr.io/foundone1/dev/sampleimage:v2
          resourceGroup: grp2
