name: docker app test

on:
 workflow_dispatch:
 workflow_call:
   inputs:
     success_msg:
       type: string 
       required: false
jobs:
  test:
   strategy:
     matrix:
       os: [ubuntu-latest,windows-latest]
       node-version: [20]
   runs-on: ${{ matrix.os }}
   steps:
     - name: checkout the repo
       uses: actions/checkout@v4
     - name: app check
       uses: actions/setup-node@v4
       with:
        node-version: ${{matrix.node-version}}
     - name: check the app
       run: |
         cd dockerFiles
         npm install
         npm start:test
     - name: check the endpoint
       run: curl -v http://localhost:3000/health
      
