name: Docker App
on:
  - workflow_dispatch

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          registry: ghcr.io
      - name: docker build
        run: |
          cd dockerFiles
          docker build . -t myapp:v1
      - name: docker dev push
        run: |
          docker tag myapp:v1 ghcr.io/foundone1/dev/sampleimage:v1
          docker push ghcr.io/foundone1/dev/sampleimage:v1
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          registry: ghcr.io
      - name: test the app
        uses: ./.github/workflows/docker-app-test.yml
      - name: pull the container and run
        run: |
          docker pull ghcr.io/foundone1/dev/sampleimage:v1
          docker run -d --name myapp -p 3000:3000 ghcr.io/foundone1/dev/sampleimage:v1

