name: docker app test

on:
 workflow_dispatch:
 workflow_call:
   inputs:
     success_msg:
       type: string 
       required: false
env:
 port: 3000
jobs:
  test:
   # strategy:
   #   matrix:
   #     os: [ubuntu-latest]
   #     node-version: [20]
   runs-on: ubuntu-latest
   steps:
     - name: checkout the repo
       uses: actions/checkout@v4
     - name: app check
       uses: actions/setup-node@v4
       with:
        node-version: 22
     - name: check the app
       run: |
         cd dockerFiles
         npm install
         npm run start
     - name: upload artifact
       uses: actions/upload-artifact@v4
       with:
         path: dockerFiles/log.txt
         name: log.txt_testCaseFrom_dockerAppTest
  test-app:
   runs-on: ubuntu-latest
   steps:
     - name: test the API
       run: |
        server=$(hostname)
        echo "server=$server" >> "GITHUB_ENV"
        sleep 5
        curl -v https://$server:${{env.port}}/health
      
