# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - app1-container

on:
  push:
    branches:
      - feature_branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_A5CA6148CDE24C9C9E4C44E26AAE4147 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_4494CA3AD08C464FB603F2737CD91CD3 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_A5CA6148CDE24C9C9E4C44E26AAE4147 }}/foundone1/dev/sampleimage:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_474774EFFA5D4785893A5C49302DC7F0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_33CF788582334393B5FD406F06203F82 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EFC3DDA66EAB4C92AD4B47556D4A23ED }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app1-container'
          slot-name: 'Production'
          images: 'ghcr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_A5CA6148CDE24C9C9E4C44E26AAE4147 }}/foundone1/dev/sampleimage:${{ github.sha }}'
          